# -*- coding: utf-8 -*-
"""Package the synthetic validation corpus for public release (Phase 5.2).

The 12 synthetic signals (`docs/validation/test_signals/`) are VoiceMap's
ground-truth corpus: each has an analytically-known answer (F0, jitter,
shimmer, formants, SNR, vibrato) recorded in `manifest.json`. They are
generated deterministically by `make_signals.py`, so they are reproducible and
not committed as binaries.

This script regenerates them and bundles signals + manifest + README + a corpus
LICENSE/CITATION into a single release archive under `result/`, ready to attach
to a GitHub release.

    python scripts/package_corpus.py
"""
import os
import sys
import zipfile

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(
    os.path.abspath(__file__))), "docs", "validation", "test_signals"))

import make_signals as ms            # noqa: E402
from voicemap.__version__ import __version__, __author__, __copyright__  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SIG_DIR = ms.OUT_DIR
OUT_DIR = os.path.join(ROOT, "result")

CORPUS_LICENSE = f"""VoiceMap Synthetic Test Corpus — License

These signals are SYNTHETIC: produced entirely by VoiceMap's own generator
(docs/validation/test_signals/make_signals.py). They contain no recorded human
voice. They are released into the public domain under Creative Commons CC0 1.0
so anyone may use them to validate or benchmark voice-analysis software.

Generator software: VoiceMap {__version__} (MIT).
{__copyright__}
"""

CITATION = f"""If you use this corpus, please cite:

  {__author__}. VoiceMap — 嗓音声学品质多维分析图谱, v{__version__}.
  Synthetic Voice Test Corpus. Generated by make_signals.py
  (source-filter synthesis with analytically-known ground truth).

Ground truth for every signal is in manifest.json.
"""


def main():
    print("Regenerating synthetic signals...")
    ms.build_all()

    wavs = sorted(f for f in os.listdir(SIG_DIR) if f.endswith(".wav"))
    if not wavs:
        raise SystemExit("no signals produced — check make_signals.py")
    extras = [f for f in ("manifest.json", "README.md")
              if os.path.exists(os.path.join(SIG_DIR, f))]

    os.makedirs(OUT_DIR, exist_ok=True)
    zip_path = os.path.join(
        OUT_DIR, f"voicemap_synthetic_corpus_v{__version__}.zip")
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as z:
        for f in wavs + extras:
            z.write(os.path.join(SIG_DIR, f), arcname=f"corpus/{f}")
        z.writestr("corpus/LICENSE.txt", CORPUS_LICENSE)
        z.writestr("corpus/CITATION.txt", CITATION)

    size_kb = os.path.getsize(zip_path) / 1024
    print(f"\nPackaged {len(wavs)} signals + {len(extras)} docs "
          f"+ LICENSE + CITATION")
    print(f"  -> {zip_path}  ({size_kb:.0f} KB)")
    print("\nGitHub release steps:")
    print(f"  gh release create corpus-v{__version__} \"{zip_path}\" \\")
    print(f"    --title \"VoiceMap synthetic test corpus v{__version__}\" \\")
    print("    --notes \"Synthetic ground-truth voice signals (CC0). "
          "See corpus/README.md + manifest.json.\"")


if __name__ == "__main__":
    main()
